# Generated by Django 5.1 on 2024-08-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('desa', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
                ('kelahiran', models.DateField()),
                ('pendidikan', models.CharField(max_length=50)),
                ('nomor_sk', models.CharField(max_length=50)),
                ('tanggal_sk', models.DateField()),
                ('NIK', models.PositiveIntegerField()),
                ('KK', models.PositiveIntegerField()),
                ('keterangan', models.CharField(max_length=50)),
            ],
        ),
    ]
