# Generated by Django 5.1 on 2024-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hp',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AlterField(
            model_name='record',
            name='KK',
            field=models.BigIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='NIK',
            field=models.BigIntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='desa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='jabatan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
